#!/usr/bin/env perl

use strict;
use warnings;
use autodie;

my $path = q{};
my $out;

while (<>) {
    if ($path ne $ARGV) {
        $path = $ARGV;
        open $out, '>', "$path.out";
    }

    print {$out} s/Fred/Larry/gir;
}

close $out;
