#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(fc);
use autodie;

my %swap = (fc 'Fred' => 'Wilma', fc 'Wilma' => 'Fred');
my $open_next = 1;
my $path = q{};
my $out;

while (<>) {
    if ($open_next) {
        $open_next = 0;
        $path = $ARGV;
        open $out, '>', "$path.out";
    }
} continue {
    print {$out} s/(Fred|Wilma)/$swap{fc $1}/gir;

    if (eof ARGV) {
        close ARGV;
        close $out;
        $open_next = 1;
    }
}
