#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(fc);
use autodie;

my %swap = (fc 'Fred' => 'Wilma', fc 'Wilma' => 'Fred');
my $path = q{};
my $out;

while (<>) {
    if ($path ne $ARGV) {
        $path = $ARGV;
        open $out, '>', "$path.out";
    }

    print {$out} s/(Fred|Wilma)/$swap{fc $1}/gir;
}

close $out;
