#!/usr/bin/env perl

use strict;
use warnings;

my %names = (
    fred => 'flintstone',
    barney => 'rubble',
    wilma => 'flintstone',
);

print 'Enter given name: ';
chomp(my $given = <>);

if (exists $names{$given}) {
    printf "The family name of $given is $names{$given}.\n";
} else {
    printf "No family name for $given is known.\n";
}
