#!/usr/bin/perl
while (<>) {                   # take one input line at a time
	chomp;
	if (/(\w*a\b)/) {
		print "Matched: |$`<$&>$'|\n";  # the special match vars
        print "\tcontains '$1'\n";
	} else {
		print "No match: |$_|\n";
	}
}
