#!/usr/bin/perl
while (<>) {                   # take one input line at a time
	chomp;
	if (/(?<word>\w*a\b)/) {
		print "Matched: |$`<$&>$'|\n";  # the special match vars
        print "\t'$_' contains '$+{$_}'\n" for keys %+;
	} else {
		print "No match: |$_|\n";
	}
}
