#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

sub mean {
    my $acc = 0;
    $acc += $_ for @_;
    $acc / @_
}

sub above_average {
    my $avg = mean @_;
    my @ret;
    for (@_) { push @ret, $_ if $avg < $_ };
    @ret;
}

my @fred = above_average 1..10;
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average 100, 1..10;
print "\@barney is @barney\n";
print "(Should be just 100)\n";
