#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

sub greet {
    state @names;
    my $cur = $_[0]; # use only the first argument

    if (@names) {
        say "Hi $cur! I've seen @names";
    } else {
        say "Hi $cur! You are the first one here!";
    }

    push @names, $cur;
}

greet $_ for qw(Fred Barney Wilma Betty);
